### ISSUE TITLE
How to install in NPP ?

### ISSUE THREAD

**Issue by MadTomT** [vinsworldcom/nppQCP#3]
As per subject how do I install this into NPP ?

Thanks

**Comment by vinsworldcom** [comment]
@MadTomT

Assuming you are running the latest Notepad++ >= 8.3:

In your Notepad++ plugins/ directory, create a directory called: "QuickColorPicker" and then put the [DLL from the appropriate ZIP file](https://github.com/vinsworldcom/nppQCP/releases/tag/2.1.2.1) into that directory.

If not:

In your Notepad++ plugins/ directory, create a directory called: "NppQCP" and then put the [DLL from the appropriate ZIP file](https://github.com/vinsworldcom/nppQCP/releases/tag/2.1.1.1) into that directory.

Cheers.

**Comment by MadTomT** [comment]
Hi Vince,

Thanks that seems to be working  :)

Tom
