### ISSUE TITLE
Does not display the colour hint in-line any longer

### ISSUE THREAD

**Issue by Chad90b** [vinsworldcom/nppQCP#4]
As the title suggests this no longer shows the color of the hex-code inside the editor itself **without** highlighting the color code unless the language chosen is XML. Is this something you are interested in resolving so that it will do this for any language? Such as Lua? It's a very beloved feature and quite frankly shocking it's not a native NPP feature at this point.

What it currently looks like:
![image](https://github.com/vinsworldcom/nppQCP/assets/68355086/b9e14746-0b83-4b6a-95bf-c2cd53d046a8)

vs

What is **should** look like:
![image](https://github.com/vinsworldcom/nppQCP/assets/68355086/a4bec4bf-1e23-4968-83d8-7897dfcf4a84)

**Comment by vinsworldcom** [comment]
Pretty sure this never worked except for CSS, JavaScript, HTML or XML:

https://github.com/vinsworldcom/nppQCP/blob/54ff006b1ff3c57aecd2427323ab0fe191d76526/NppQCP.cpp#L785-L789

Cheers.

**Comment by vinsworldcom** [comment]
Newer Notepad++ has enabled [DirectWrite](https://www.scintilla.org/ScintillaDoc.html#SCI_SETTECHNOLOGY) by default.  This prevents the current implementation from drawing the underlines.  The easiest way to get around this is to disable DirectWrite:

![image](https://github.com/vinsworldcom/nppQCP/assets/9657169/8eec3fb9-3b14-4402-9fc4-59c23bf5737f)

Or you can do this dynamically per Scintilla buffer if you have [NppExec](https://github.com/d0vgan/nppexec) or [PythonScript](https://github.com/bruderstein/PythonScript/) installed.

+ [NppExec](https://github.com/d0vgan/nppexec)
```
SCI_SENDMSG SCI_SETTECHNOLOGY SC_TECHNOLOGY_DEFAULT
```

+ [PythonScript](https://github.com/bruderstein/PythonScript/)
```
editor.setTechnology(TECHNOLOGY.DEFAULT)
```

use `SC_TECHNOLOGY_DIRECTWRITE` and `TECHNOLOGY.DIRECTWRITE` respectively with the above commands to re-enable the new Notepad++ default (DirectWrite on).

Cheers.

**Comment by ShieldzieeForever** [comment]
> Newer Notepad++ has enabled [DirectWrite](https://www.scintilla.org/ScintillaDoc.html#SCI_SETTECHNOLOGY) by default. This prevents the current implementation from drawing the underlines. The easiest way to get around this is to disable DirectWrite:
> 
> ![image](https://private-user-images.githubusercontent.com/9657169/287139135-8eec3fb9-3b14-4402-9fc4-59c23bf5737f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NzA5MzcsIm5iZiI6MTcwNjg3MDYzNywicGF0aCI6Ii85NjU3MTY5LzI4NzEzOTEzNS04ZWVjM2ZiOS0zYjE0LTQ0MDItOWZjNC01OWMyM2JmNTczN2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMTA0MzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjFiZWMzMGM3ODUxN2M5ZWZjOTQxNGQ0MmU1MDQ5ODljOTJmM2VjY2U2NTAzYmFlMzJmZDQ5OTkzNzY5ZmNkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mrcsZ3SlhRgAqIOjOeSVqQlMhk3jmyF5EOgb0gq4NHw)
> 
> Or you can do this dynamically per Scintilla buffer if you have [NppExec](https://github.com/d0vgan/nppexec) or [PythonScript](https://github.com/bruderstein/PythonScript/) installed.
> 
>     * [NppExec](https://github.com/d0vgan/nppexec)
> 
> 
> ```
> SCI_SENDMSG SCI_SETTECHNOLOGY SC_TECHNOLOGY_DEFAULT
> ```
> 
>     * [PythonScript](https://github.com/bruderstein/PythonScript/)
> 
> 
> ```
> editor.setTechnology(TECHNOLOGY.DEFAULT)
> ```
> 
> use `SC_TECHNOLOGY_DIRECTWRITE` and `TECHNOLOGY.DIRECTWRITE` respectively with the above commands to re-enable the new Notepad++ default (DirectWrite on).
> 
> Cheers.

This 100% fixes it. Thank you!
