### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by haizen007** [vinsworldcom/nppQCP#5]
I added the folder and the dll in plugin but the app crashes when I try to open it
C:\Program Files\Notepad++\plugins\NppQCP\NppQCP.dll

**Comment by vinsworldcom** [comment]
You're not using the latest version as the name is not `NppQCP.dll`.

Also see #4 

Cheers.

**Comment by haizen007** [comment]
> You're not using the latest version as the name is not `NppQCP.dll`.
> 
> Also see #4
> 
> Cheers.

I downloaded the version available  [[Download from Amazon Mirror]](https://s3-ap-southeast-1.amazonaws.com/nppqcp/nppqcp-2.0.zip)

guessa was misleading

**Comment by vinsworldcom** [comment]
That Amazon mirror version is not mine.
