### ISSUE TITLE
Scintilla headers changed v8.6.2

### ISSUE THREAD

**Issue by Stephanowicz** [vinsworldcom/nppQCP#6]
Hi there!

Just realized that the headers changed again.
Needs some update for the scintilla definitions:
```
(from scintilla.h)
// Deprecated by Notepad++ 2GB+ support via new scintilla interfaces from 5.2.3 (see https://www.scintilla.org/ScintillaHistory.html)
// Please use Sci_Position, SCI_GETTEXTRANGEFULL, SCI_FINDTEXTFULL, and SCI_FORMATRANGEFULL and corresponding defines/structs
```

After updating the headers in "Shared" and fixing them in NppQCP.cpp everything compiles fine and is working again in NPP 8.6.2

EDIT: I downloaded the pluginTemplate - this has the annotations posted above.
But the github master still has both definitions... idk ???
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/632dcaa4706654584222835bef6ea7715a60402d/scintilla/include/Scintilla.h#L494

Nevertheles one needs to recompile with new headers to get it work with 8.6.2

Cheers, Stephan

**Comment by vinsworldcom** [comment]
Yes, I believe [this commit on the develop branch](https://github.com/vinsworldcom/nppQCP/commit/9abdf6207d97ceee44f60316197e4d3f21c63b16) addresses this.

**Comment by dodmi** [comment]
Really off topic, but as I saw, you're fixing up some old unmaintained plugins - I'm a happy new user of your nppQCP version.
Could you please have a look at https://github.com/crypto-rsa/XmlNavigator
I'm trying to switch to the x64 version of NPP, but the x64 build of this plugin doesn't work. And in my opinion, Xml Treeview is no match to XML Navigator.

**Comment by vinsworldcom** [comment]
@dodmi , I took a quick look and that plug-in is written in C#.  I'm barely a C++ developer and the only experience I have with C# is it well behaved working plug-in that did not have the features I wanted. 

I'm afraid debugging why a C# plugin does not work is a bit be on my skill set.

Cheers.
